<a href="https://colab.research.google.com/github/noushadkhan01/Grokking-Deep-Learning/blob/master/Chapter6%20-%20Intro%20to%20Backpropagation%20-%20Building%20Your%20First%20DEEP%20Neural%20Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating a Matrix or Two in Python

In [1]:
import numpy as np
weights = np.array([0.5,0.48,-0.7])
alpha = 0.1

streetlights = np.array( [ [ 1, 0, 1 ],
                           [ 0, 1, 1 ],
                           [ 0, 0, 1 ],
                           [ 1, 1, 1 ],
                           [ 0, 1, 1 ],
                           [ 1, 0, 1 ] ] )

walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0 ] )

input = streetlights[0] # [1,0,1]
goal_prediction = walk_vs_stop[0] # equals 0... i.e. "stop"

for iteration in range(20):
    prediction = input.dot(weights)
    error = (goal_prediction - prediction) ** 2
    delta = prediction - goal_prediction
    weights = weights - (alpha * (input * delta))	

    print("Error:" + str(error) + " Prediction:" + str(prediction))

Error:0.03999999999999998 Prediction:-0.19999999999999996
Error:0.025599999999999973 Prediction:-0.15999999999999992
Error:0.01638399999999997 Prediction:-0.1279999999999999
Error:0.010485759999999964 Prediction:-0.10239999999999982
Error:0.006710886399999962 Prediction:-0.08191999999999977
Error:0.004294967295999976 Prediction:-0.06553599999999982
Error:0.002748779069439994 Prediction:-0.05242879999999994
Error:0.0017592186044416036 Prediction:-0.04194304000000004
Error:0.0011258999068426293 Prediction:-0.03355443200000008
Error:0.0007205759403792803 Prediction:-0.02684354560000002
Error:0.0004611686018427356 Prediction:-0.021474836479999926
Error:0.0002951479051793508 Prediction:-0.01717986918399994
Error:0.00018889465931478573 Prediction:-0.013743895347199997
Error:0.00012089258196146188 Prediction:-0.010995116277759953
Error:7.737125245533561e-05 Prediction:-0.008796093022207963
Error:4.951760157141604e-05 Prediction:-0.007036874417766459
Error:3.169126500570676e-05 Prediction:-0.0

## Building Our Neural Network

In [0]:
import numpy as np

a = np.array([0,1,2,1])
b = np.array([2,2,2,3])

print(a*b) #elementwise multiplication
print(a+b) #elementwise addition
print(a * 0.5) # vector-scalar multiplication
print(a + 0.5) # vector-scalar addition

[0 2 4 3]
[2 3 4 4]
[0.  0.5 1.  0.5]
[0.5 1.5 2.5 1.5]


# Learning the whole dataset!

In [18]:
import numpy as np

weights = np.array([0.5,0.48,-0.7])
alpha = 0.1

streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ],
                          [ 0, 1, 1 ],
                          [ 1, 0, 1 ] ] )

walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0 ] )

input = streetlights[0] # [1,0,1]
goal_prediction = walk_vs_stop[0] # equals 0... i.e. "stop"

for iteration in range(40):
    error_for_all_lights = 0
    print('-'*80)
    print(f'Iteration No.:-- {iteration + 1}')
    print('-'*40)
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_prediction = walk_vs_stop[row_index]
        
        prediction = input.dot(weights)
        
        error = (goal_prediction - prediction) ** 2
        error_for_all_lights += error
        
        delta = prediction - goal_prediction
        weights = weights - (alpha * (input * delta))
        print(f'Prediction: for row {row_index + 1}:--- {prediction}')
    print(f'Total Error for Iteration {iteration + 1}:-- {error_for_all_lights}')
    print('-'*80)

--------------------------------------------------------------------------------
Iteration No.:-- 1
----------------------------------------
Prediction: for row 1:--- -0.19999999999999996
Prediction: for row 2:--- -0.19999999999999996
Prediction: for row 3:--- -0.5599999999999999
Prediction: for row 4:--- 0.6160000000000001
Prediction: for row 5:--- 0.17279999999999995
Prediction: for row 6:--- 0.17552
Total Error for Iteration 1:-- 2.6561231104
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Iteration No.:-- 2
----------------------------------------
Prediction: for row 1:--- 0.14041599999999999
Prediction: for row 2:--- 0.3066464
Prediction: for row 3:--- -0.34513824
Prediction: for row 4:--- 1.006637344
Prediction: for row 5:--- 0.4785034751999999
Prediction: for row 6:--- 0.26700416768
Total Error for Iteration 2:-- 0.9628701776715985
-----------------------------------

# Our First "Deep" Neural Network

In [34]:
#chekc how weight initialization works by numpy
import numpy as np
hidden_size = 4
input_shape = (4, 3)
weights_0_1 = 2*np.random.random((input_shape[1], hidden_size)) - 1
weights_0_1

array([[-0.63859465, -0.54377641,  0.54211674,  0.7861175 ],
       [ 0.8436779 , -0.21851777,  0.90240112,  0.08632561],
       [-0.24578449,  0.89605952, -0.35572276,  0.00566086]])

In [0]:
import numpy as np

np.random.seed(1)


#define activation function 
def relu(x):
    return (x > 0) * x #returns 0 if x < 0, return x if x > 0


alpha = 0.2

#initialize no. of neurons in first hidden layer
hidden_size = 4

streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ] ] )

#we are making neural network for just 1 row now. wich have three elements
input = streetlights[0]

#we are transposing it because it's two dimensional array for our output we need row vector, corresponding to every row
walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

#initialize weight for hiden layer1
weights_0_1 = 2*np.random.random((input.shape[1], hidden_size)) - 1

#initialize weight for hidden layer2
weights_1_2 = 2*np.random.random((hidden_size, 1)) - 1

#input layer
layer_0 = input

#output for hidden layer1
layer_1 = relu(np.dot(layer_0,weights_0_1)) #apply relu activation to the output of 2nd layer

#output for output layer layer
layer_2 = np.dot(layer_1,weights_1_2)

## Backpropagation in Code

In [0]:
import numpy as np


np.random.seed(1)

def relu(x):
    return np.max(0, x)# returns x if x > 0
                       # return 0 otherwise

def relu2deriv(output):
    return output > 0 # returns 1 for input > 0
                    # return 0 otherwise
alpha = 0.2
hidden_size = 4
X = streetlights
y = walk_vs_stop
#initialize weights for hidden layer 1 and output layer
weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_output = 2*np.random.random((hidden_size,1)) - 1

for iteration in range(60):
  layer_2_error = 0
  for i in range(len(X)):
    #get 2-D array for input layer
    layer_0 = X[i:i+1]

    #dot product of layer_0 and layer2
    layer_1 = relu(np.dot(layer_0, weights_0_1))

    #dot product of layer 2 and output layer
    output_layer = np.dot(layer_1, weights_output) #it will return (1, 1) 2d array because we are doing separately for every row

    #calculate error for every row and sum it
    #its output layer
    output_layer_error += np.sum((output_layer - y[i:i+1]) ** 2) #subtracting numpy array for input and output(it will return 2d array of shape (1, 1))

    #we are calculating delta for every row separately in a loop so.......
    output_layer_delta = (y[i:i+1] - output_layer)

    layer_1_delta = output_layer_delta.dot(weights_output.T)*relu2deriv(layer_1)

    weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
    weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
  if(iteration % 10 == 9):
    print("Error:" + str(layer_2_error))

Error:0.6342311598444467
Error:0.35838407676317513
Error:0.0830183113303298
Error:0.006467054957103705
Error:0.0003292669000750734
Error:1.5055622665134859e-05


In [36]:
i = 0
streetlights[i:i+1]

array([[1, 0, 1]])

In [38]:
streetlights[0]

array([1, 0, 1])

## One Iteration of Backpropagation

In [0]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x 

def relu2deriv(output):
    return output>0 

lights = np.array( [[ 1, 0, 1 ],
                    [ 0, 1, 1 ],
                    [ 0, 0, 1 ],
                    [ 1, 1, 1 ] ] )

walk_stop = np.array([[ 1, 1, 0, 0]]).T

alpha = 0.2
hidden_size = 3

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

layer_0 = lights[0:1]
layer_1 = np.dot(layer_0,weights_0_1)
layer_1 = relu(layer_1)
layer_2 = np.dot(layer_1,weights_1_2)

error = (layer_2-walk_stop[0:1])**2

layer_2_delta=(layer_2-walk_stop[0:1])

layer_1_delta=layer_2_delta.dot(weights_1_2.T)
layer_1_delta *= relu2deriv(layer_1)

weight_delta_1_2 = layer_1.T.dot(layer_2_delta)
weight_delta_0_1 = layer_0.T.dot(layer_1_delta)

weights_1_2 -= alpha * weight_delta_1_2
weights_0_1 -= alpha * weight_delta_0_1

### Putting it all Together

In [0]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x # returns x if x > 0
                       # return 0 otherwise

def relu2deriv(output):
    return output>0 # returns 1 for input > 0
                    # return 0 otherwise

streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ] ] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T
    
alpha = 0.2
hidden_size = 4

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

for iteration in range(60):
   layer_2_error = 0
   for i in range(len(streetlights)):
      layer_0 = streetlights[i:i+1]
      layer_1 = relu(np.dot(layer_0,weights_0_1))
      layer_2 = np.dot(layer_1,weights_1_2)

      layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)

      layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])
      layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)

      weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
      weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)

   if(iteration % 10 == 9):
      print("Error:" + str(layer_2_error))

Error:0.6342311598444467
Error:0.35838407676317513
Error:0.0830183113303298
Error:0.006467054957103705
Error:0.0003292669000750734
Error:1.5055622665134859e-05
